name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: running a one line sccript
        run : echo Hello, Akshay kumar
      
      #Below  is the composite action usage 
      - name: running composite action
        uses: KumarAkshayThakur/CompositeAction@main 
      
      #Below is using resuable workflow
      - name: running reusable workflow
        uses: KumarAkshayThakur/ReusableWorkflow/.github/workflows/reusableworkflow.yml@main
