name: learn-github-actions
on: [push,workflow_dispatch]
#on: [workflow_dispatch]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: running a one line sccript
        run : echo Hello, Akshay kumar thakur
      
      #Below  is the composite action usage 
      - name: running composite action
        uses: KumarAkshayThakur/CompositeAction@main 
      
      #Below is using resuable workflow
  test: 
    needs: [check-bats-version]
    uses: KumarAkshayThakur/ReusableWorkflow/.github/workflows/reusableworkflow.yml@main
